name: Build and Upload

on:
  push:
    branches:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        # 从分支名中获取版本号release/v1.0.0 => 1.0.0
        run: echo "VERSION=$(echo $BRANCH_NAME | sed 's/release\/v//g')" >> $GITHUB_ENV

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: LCAP_LIB_VERSION=${{ env.VERSION }} npm run build

      # 创建一个临时目录
      - name: Create Assets
        run: LCAP_LIB_VERSION=${{ env.VERSION }} node scripts/assets.mjs

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lcap-ui@${{ env.VERSION }}
          path: lcap-ui@${{ env.VERSION }}

  call-tyler:
    needs: build
    uses: netease-lcap/tyler/.github/workflows/release-ui-libraries.yml@master
    secrets: inherit
